version: '3.7'

services:

    client:
      build:
         context: ./frontend
         dockerfile: Dockerfile
      tty: true
      ports:
         - "3000:3000"
      volumes:
         - ./frontend:/app
         - /app/node_modules

    api:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        command: flask run
        ports:
            - "5000:5000"
        environment:
            FLASK_APP: app.py
        networks:
            - frontend
            - backend

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge