version: '3.7'

services:

    client:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        tty: true
        ports:
            - "3000:3000"
        volumes: 
            - ./frontend:/app
            - /app/node_modules
        networks:
            - frontend

    api:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        command: flask run --host=0.0.0.0
        ports:
            - "5000:5000"
        environment:
            - FLASK_APP=app.py
            - FLASK_DEBUG=1
        networks:
            - frontend
            - backend
        volumes:
            - ./backend:/app

        env_file:
            - ./backend/.env

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge